Repository NJACKWinterOfCode/JS-OS, pull requests merged in 2019-12, with the labels that each got.

#6 Resolved Conflicts & Updated packages
  package-lock.json
  package.json
  src/applauncher/applauncher.js
  src/defaultapps/explorer/explorer.js
  src/defaultapps/terminal/terminal.js
  src/defaultapps/texteditor/editor.js
  src/desktop/contextmenu.js
  src/desktop/desktop.js
  src/desktop/taskbar/taskbar.js
  src/desktop/taskbaricon/taskbaricon.js
  src/filesystem/main.js
  src/handlers.js
  src/misc/misc.js
  src/window/window.js
Labels: NWOC, Points:5

#7 update readme
  README.md
Labels: NWOC, Points:1

#9 [WIP] Redesign the terminal
  src/defaultapps/terminal/commands.js
  src/defaultapps/terminal/terminal.css
  src/defaultapps/terminal/terminal.js
  src/filesystem/fs.json
Labels: NWOC, Points:20
